import { useState, useEffect, useRef } from "react";
import { QRCodeCanvas } from "qrcode.react";
import { motion, AnimatePresence } from "framer-motion";
import { Download, CheckCircle2 } from "lucide-react";

interface QRCodeShareProps {
  url: string;
}

export function QRCodeShare({ url }: QRCodeShareProps) {
  const [isGenerating, setIsGenerating] = useState(true);
  const [showToast, setShowToast] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  // Fake generation delay for premium skeleton feel
  useEffect(() => {
    setIsGenerating(true);
    const timer = setTimeout(() => {
      setIsGenerating(false);
    }, 600);
    return () => clearTimeout(timer);
  }, [url]);

  const handleDownload = () => {
    if (!canvasRef.current) return;
    
    // The canvas generated by qrcode.react has the drawn QR code
    const canvas = canvasRef.current;
    const pngUrl = canvas
      .toDataURL("image/png")
      .replace("image/png", "image/octet-stream");
      
    const downloadLink = document.createElement("a");
    downloadLink.href = pngUrl;
    downloadLink.download = "birthday-bloom-qr.png";
    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);

    // Show success toast
    setShowToast(true);
    setTimeout(() => {
      setShowToast(false);
    }, 3000);
  };

  return (
    <div className="relative glass-card rounded-2xl p-4 flex flex-col items-center border border-primary/10 shadow-sm mt-6">
      <div className="relative mb-3 flex justify-center items-center rounded-xl overflow-hidden bg-white/50 p-2 border border-black/5" style={{ minHeight: "160px", minWidth: "160px" }}>
        
        {isGenerating ? (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-black/5 animate-pulse rounded-xl"
          />
        ) : (
          <motion.div
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ type: "spring", damping: 20, stiffness: 300 }}
          >
            {/* The canvas is rendered at high resolution but scaled down for display */}
            <div style={{ display: 'none' }}>
               {/* We wrap it in a hidden container to grab the ref, wait, QRCodeCanvas itself accepts ref but it might be easier to wrap it in a visible container that controls size */}
            </div>
            
            <QRCodeCanvas
              ref={canvasRef}
              value={url}
              size={1024}
              level="H"
              marginSize={2}
              style={{ width: "160px", height: "160px", borderRadius: "8px" }}
            />
          </motion.div>
        )}
      </div>

      <p className="text-xs text-foreground/50 font-medium tracking-wide text-center uppercase mb-3">
        Scan to open this Birthday Bloom
      </p>

      <button
        onClick={handleDownload}
        disabled={isGenerating}
        className="w-full flex items-center justify-center gap-2 bg-primary/10 hover:bg-primary/20 text-primary font-semibold py-2.5 px-4 rounded-xl transition-colors disabled:opacity-50 disabled:cursor-not-allowed group"
      >
        <Download size={16} className="group-hover:-translate-y-0.5 transition-transform" />
        Download QR
      </button>

      {/* Success Toast */}
      <AnimatePresence>
        {showToast && (
          <motion.div
            initial={{ opacity: 0, y: 10, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 10, scale: 0.95 }}
            className="absolute -top-12 left-1/2 -translate-x-1/2 bg-foreground text-background text-xs font-semibold px-4 py-2 rounded-full shadow-lg flex items-center gap-2 whitespace-nowrap z-10"
          >
            <CheckCircle2 size={14} className="text-green-400" />
            QR Code downloaded successfully!
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
